name: Release Docker Images
on:
  push:
    branches:
      - main
    paths:
      - "python/sglang/version.py"
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'choronz/sglang'
    runs-on: ubuntu-latest
    environment: 'prod'
    strategy:
      matrix:
        cuda_version: ['12.4.1']
        build_type: ['all']  # srt
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          version=$(cat python/sglang/version.py | cut -d'"' -f2)
          if [ "${{ matrix.cuda_version }}" = "12.4.1" ]; then
            cuda_tag="cu124"
          else
            echo "Unsupported CUDA version"
            exit 1
          fi
          tag=v${version}-${cuda_tag}

          docker build . -f docker/Dockerfile --build-arg CUDA_VERSION=${{ matrix.cuda_version }} --build-arg BUILD_TYPE=${{ matrix.build_type }} -t kairos333/sglang:${tag}${tag_suffix} --no-cache
          docker push kairos333/sglang:${tag}${tag_suffix}
          
          # if [ "${{ matrix.cuda_version }}" = "12.4.1" ]; then
          #   docker tag kairos333/sglang:${tag}${tag_suffix} kairos333/sglang:latest${tag_suffix}
          #   docker push kairos333/sglang:latest${tag_suffix}
          # fi
