name: Release PyPI
on:
  push:
    branches:
      - main
    paths:
      - "python/sglang/version.py"
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'choronz/sglang'
    runs-on: ubuntu-latest
    environment: 'prod'
    steps:
      - name: Set up python3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Upload to pypi
        run: |
          cd python
          cp ../README.md ../LICENSE .
          pip install build
          python3 -m build
          pip install twine
          # python3 -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
